# Placeholder. During install, replace this file with the one generated by:
#   nixos-generate-config --root /mnt
#   cp /mnt/etc/nixos/hardware-configuration.nix hosts/rognix/
# Then commit it so the box is reproducible.
throw "hosts/rognix/hardware-configuration.nix is a placeholder: replace it with nixos-generate-config output (see README.md)"
